version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks: 
      - redcoins-network

  app:
    build: .
    command: sh -c "/app/redcoins"
    ports:
      - "${PORT}:${PORT}"
    depends_on: 
      - db
    networks: 
      - redcoins-network
  
networks:
  redcoins-network:
    driver: bridge
