version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'redcoinsdb'
      MYSQL_USER: 'redcoins'
      MYSQL_PASSWORD: 'redcoins@!'
      MYSQL_ROOT_PASSWORD: 'p@ssw0rd!'
    ports:
      - '3306:3306'