version: '3.3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'redcoinsdb'
      MYSQL_USER: 'redcoins'
      MYSQL_PASSWORD: 'redcoins'
      MYSQL_ROOT_PASSWORD: 'p@ssw0rd!'
    ports:
      - '3306:3306'
    networks: 
      - redcoins-network

  app:
    build: .
    command: sh -c "/app/redcoins"
    ports:
      - "8080:8080"
    depends_on: 
      - db
    networks: 
      - redcoins-network
  
networks:
  redcoins-network:
    driver: bridge
